### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by gokulavelan** [ThanhHung2112/LMS#1]
Give the installation guide and requirements.

**Comment by ThanhHung2112** [comment]
Check this [guide](https://docs.google.com/document/d/1-6CWZIH3tAfjefyjPojpbRn2zMGBLLKlyr0pNBjxgoY/edit?fbclid=IwAR3qhrwKdev-F_k2IrBirUCMVWfyNd0OuHjH4xyeFK3cbJIDaehIUGUdClU)  ( in vietnamese ) for installtion. An english version will be upload later

**Comment by gokulavelan** [comment]
Thanks

**Comment by gokulavelan** [comment]
The provided database contains data only. It has some extras tables compared to the moodle's default database.

**Comment by LBQTrung** [comment]
To facilitate the AI feature demo, the developer decided to create additional tables with the prefix mdl_demo. Here, you just need to download the [database.sql](https://drive.google.com/file/d/1MoqW56mVGOzqqDBIvO5lxoO4TcpMcRAy/view?usp=drive_link) file and run it on the Moodle database (using any database management tool, such as HeidiSQL).
