### ISSUE TITLE
Could not install it on windows

### ISSUE THREAD

**Issue by meedrazzouq** [ThanhHung2112/LMS#3]
Hello,

I followed all the instructions in the installation instructions file but  many errors found.
Is this project still can be run locally?

**Comment by ThanhHung2112** [comment]
Hi @meedrazzouq , could you please provide more details about the issue you're encountering ?

**Comment by meedrazzouq** [comment]
@ThanhHung2112  can you please help me run it because I could do not do it. I can pay for that if you want

**Comment by ThanhHung2112** [comment]
@meedrazzouq  My team is away now, If you getting any problem, just push it here, they will help
